# set system to "etcd", "cassandra", or "antidote"
system = "cassandra"
workload = "balanced"
duration_seconds = 60
concurrency = 4
output_file = "results.csv"

# Optional: remove this section to run without fault injection
[fault]
# set file path to match system (i.e "etcd", "cassandra", or "antidote")
script = "scripts/cassandra/kill_node.sh"
trigger_at_seconds = 30