version: "3.8"

services:
  antidote1:
    image: antidotedb/antidote
    container_name: antidote1
    ports:
      - "8087:8087"
    networks:
      - antidote-net
    environment:
      - NODE_NAME=antidote@antidote1
      - COOKIE=consistency-lab-cookie

  antidote2:
    image: antidotedb/antidote
    container_name: antidote2
    ports:
      - "8088:8087"
    networks:
      - antidote-net
    environment:
      - NODE_NAME=antidote@antidote2
      - COOKIE=consistency-lab-cookie
    depends_on:
      - antidote1

  antidote3:
    image: antidotedb/antidote
    container_name: antidote3
    ports:
      - "8089:8087"
    networks:
      - antidote-net
    environment:
      - NODE_NAME=antidote@antidote3
      - COOKIE=consistency-lab-cookie
    depends_on:
      - antidote1

networks:
  antidote-net:
    driver: bridge
